name: 'data_governance_platform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'data_governance_platform'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/reference/model-configs
models:
  data_governance_platform:
    # Staging models - explicitly set to STAGING schema
    staging:
      +materialized: table
      +schema: "STAGING"
      +tags: ["staging", "silver"]
      +meta:
        owner: "data-team"
        layer: "staging"
    # Mart models - explicitly set to MART schema
    mart:
      +materialized: table
      +schema: "MART"
      +tags: ["mart", "gold"]
      +meta:
        owner: "data-team"
        layer: "mart"

# Variables for the project
vars:
  # Date range for analysis
  start_date: '2024-01-01'
  end_date: '2024-12-31'
  
  # Data quality thresholds (updated for larger dataset)
  min_customer_count: 1000
  max_null_percentage: 5
  
  # Business rules
  min_order_amount: 0.01
  max_order_amount: 10000.00
  
  # Performance settings for larger dataset
  batch_size: 10000
  max_rows_per_batch: 50000

# Global configuration for Snowflake
on-run-start: "{{ log('Starting dbt run', info=true) }}"
on-run-end: "{{ log('Completed dbt run', info=true) }}"

# Quoting configuration to handle Snowflake case sensitivity and spaces in identifiers
quoting:
  database: true  # Must be true for database names with spaces (e.g., "DATA PLATFORM XYZ")
  schema: false
  identifier: false

# dbt Lineage Configuration
# This creates metadata tables in Snowflake for lineage tracking
# Lineage is automatically created when models are run