data_governance_platform:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      authenticator: snowflake
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'DATA PLATFORM XYZ') }}"
      warehouse: "COMPUTE_WH"
      schema: "PUBLIC"
      threads: 4
      client_session_keep_alive: False
      query_tag: "dbt_dev"
      quote_identifiers: true
